[tool.poetry]
name = "python-runner-bot"
version = "0.1.0"
description = "Telegram bot to run Python code via docker containers"
# authors = ["Evgeny https://github.com/NEK-RA", "Ivan https://github.com/Brooklyn265t"]
authors = ["Evgeny", "Ivan"]
readme = "README.md"
include = [
    { path = "strings.json", format = ["sdist", "wheel"] }
]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "1.0.1"
docker = "^7.0.0"
aiogram = "^3.5.0"
requests = "2.31.0"
sphinx = "^7.3.7"

[tool.poetry.group.dev.dependencies]
pytest = "7.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bot = "python_runner_bot.bot:start"
